name: Render markdown as PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: install markdown2pdf
      run: |
        pip install markdown2pdf
    - name: Render PDF
      run: |
        md2pdf README.md --theme=github
