name: Render markdown as PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip
    - name: install markdown2pdf
      run: |
        pip3 install markdown2pdf
    - name: Render PDF
      run: |
        pwd
        ls
        md2pdf ./README.md --theme=github
