name: Render markdown as PDF

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: install md2pdf
      run: |
        pip install md2pdf
    - name: Render PDF
      run: |
        curl https://raw.githubusercontent.com/jfthuong/markdown2pdf/master/markdown2pdf/themes/github.css -o ./github.css
        md2pdf --css=github.css README.md README.pdf
        cd Homework_6/
        md2pdf --css=github.css README.md README.pdf
        cd ~/    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "PDF Generator"
        git add .
        git commit -m "Updated PDF ver. of README" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}    
    
